### ISSUE TITLE
Надо как-то проверять mix/max-width на адекватность

### ISSUE THREAD

**Issue by ingwer** [iMega/sensible-breakpoints#4]
потому что иначе получаем от
```
user@pc:~/work/src/github.com/ingwer/sensible-breakpoints/cmd$ go build && ./cmd  --max-width 200 ../test-images/aveiro_praia_da_costa_nova.jpg 
Breakpoints
#  Width     Size
1  -1649827  181 kB
2  -1095527  161 kB
3  -681698   141 kB
4  -387825   121 kB
5  -193391   101 kB
6  -77879    81 kB
7  -20771    61 kB
8  -1552     41 kB
9  291       21 k
```

и до
```
user@pc:~/work/src/github.com/ingwer/sensible-breakpoints/cmd$ go build && ./cmd  --max-width 2000 ../test-images/aveiro_praia_da_costa_nova.jpg 
panic: values in x must be in ascending order

goroutine 1 [running]:
github.com/cnkei/gospline.newSpline(0xc0003ba040, 0x8, 0x8, 0xc0003ba000, 0x8, 0x8, 0x1, 0x0, 0x0, 0xc000012300, ...)
        /home/user/go/pkg/mod/github.com/cnkei/gospline@v0.0.0-20180929110753-23435f75ed52/cubic.go:116 +0x1f2
github.com/cnkei/gospline.NewNaturalCubicSpline(...)
        /home/user/go/pkg/mod/github.com/cnkei/gospline@v0.0.0-20180929110753-23435f75ed52/cubic.go:47
github.com/cnkei/gospline.NewCubicSpline(...)
        /home/user/go/pkg/mod/github.com/cnkei/gospline@v0.0.0-20180929110753-23435f75ed52/cubic.go:39
github.com/iMega/sensible-breakpoints.createCubicSpline(0xc000012300, 0x8, 0x8, 0x8, 0x62c058)
        /home/user/work/src/github.com/ingwer/sensible-breakpoints/spline.go:33 +0x257
github.com/iMega/sensible-breakpoints.CalcBreakpoints(0x7ffd5a319ef4, 0x2d, 0x4e20, 0x0, 0x140, 0x7d0, 0x9e6010, 0x0, 0x0, 0xc0001c0600, ...)
        /home/user/work/src/github.com/ingwer/sensible-breakpoints/breakpoints.go:59 +0x1b2
main.run(0x9a51a0, 0xc0001c0660, 0x1, 0x3, 0x0, 0x0)
        /home/user/work/src/github.com/ingwer/sensible-breakpoints/cmd/main.go:56 +0x15a
github.com/spf13/cobra.(*Command).execute(0x9a51a0, 0xc000012090, 0x3, 0x3, 0x9a51a0, 0xc000012090)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x9a51a0, 0x9bbfb9, 0x61d22a, 0x4)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.Execute()
        /home/user/work/src/github.com/ingwer/sensible-breakpoints/cmd/main.go:45 +0x295
main.main()
        /home/user/work/src/github.com/ingwer/sensible-breakpoints/cmd/main.go:52 +0x20
```

**Comment by ingwer** [comment]
Паника происходит, т.к. при ресайзе картинки без опции Enlarge: true bimg не увеличивает картинку больше оригинального размера. В результате несколько точек для построения сплайна оказываются одинаковыми, и gospline паникует, т.к. требует _строго_ возрастающий порядок точек.
